version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: nm-tui
    main: ./cmd/nm-tui/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_7

archives:
  - id: nm-tui
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}"
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: alphameo
    name: nm-tui
